### ISSUE TITLE
Kafka Trigger Node Stops Listening After Some Time

### ISSUE THREAD

**Issue by hyusufyavuz** [n8n-io/n8n#13823]
### Bug Description

The Kafka Trigger node in n8n stops listening to Kafka messages after a certain period of time. Once the node stops listening, it does not resume or reconnect to Kafka unless the workflow is manually restarted. This issue makes it unreliable for long-running workflows that rely on continuous message consumption from Kafka.

The Kafka topic is storing data from Debezium CDC. It's common for the topic to receive no messages for up to half a day. Despite this, the Kafka Trigger node fails to resume listening when new messages eventually arrive after a long idle period.

Additionally, the Kafka connection is established using SASL authentication, which may affect how connections are managed and re-established.

When monitoring the consumer groups with Conduktor, it can be observed that after some time, the consumer groups fall into an empty state, and the lag starts increasing, indicating that the consumer is no longer actively consuming messages from the topic.

![Image](https://github.com/user-attachments/assets/26ce0570-b2eb-4e34-81b2-be1e49df1066)

### To Reproduce

1. Set up a Kafka Trigger node in an n8n workflow to listen to messages from a Kafka topic receiving data from Debezium CDC.
2. Deploy the workflow and leave it running for an extended period of time (several hours or longer).
3. Allow the Kafka topic to have periods of no new messages for several hours.
4. Observe that the node stops receiving messages when new data eventually arrives, with no errors or logs indicating the cause.
5. Manually restart the workflow to restore message consumption.

### Expected behavior

The Kafka Trigger node should continuously listen to Kafka messages without interruption unless explicitly stopped by the user, even when the Kafka topic remains idle for extended periods.

### Operating System

Ubuntu 22.04

### n8n Version

1.72.1

### Node.js Version

18.20.5

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @hyusufyavuz,

We have created an internal ticket to look into this which we will be tracking as "GHC-1142"

**Comment by dvargas-mono** [comment]
@hyusufyavuz 
The error is in the node station update. [PR](https://github.com/n8n-io/n8n/pull/6175)

A temporary solution is to downgrade the node version from "typeVersion": 1.1 to "typeVersion": 1.
I do this by copying the node and modifying the JSON.

![Image](https://github.com/user-attachments/assets/a6bff464-16bf-4b56-ab57-d6e25d61ef2d)

**Comment by hyusufyavuz** [comment]
@dvargas-mono  Thank you for the responses and suggestions. 

We will try updating n8n to the latest version and testing again. In the meantime, to avoid disruptions to our operations, we have implemented an alternative solution by using webhooks to send requests to n8n from another application that is listening to Kafka CDC topics.

Aside from the Kafka issue, we are also experiencing a problem where some workflows do not complete even though we have set timeouts. These executions take excessively long to finish. We are currently investigating this and may open a separate issue if necessary.

**Comment by janober** [comment]
Fix got released with [`n8n@1.87.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.87.0)

**Comment by dovandap** [comment]
> Fix got released with [`n8n@1.87.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.87.0)

Dear @janober ,

I'm currently using n8n version 1.98.1. My main workflow is checking Kafka topic message consumption. I'm using a Kafka Trigger node and Redis to receive messages. I've noticed that after a certain period, the workflow stops receiving messages. I've tried pushing around 1000 messages to the Kafka topic and then activating the workflow. It only receives about 900 messages and then stops receiving any more. Other times, it only receives a few messages before stopping entirely. Please help me investigate this.

I've already tried creating a separate project using kafkajs and it successfully receives all messages. Do you have any ideas about this issue?

**Comment by isnandar1471** [comment]
Hello, are others still experiencing the same thing until now?

**Comment by VladimirBeliakov** [comment]
I tried using this Kafka node and ran into the same problem with one slight difference:
> Allow the Kafka topic to have periods of no new messages for several hours.

In my case the topic the node was reading from is pretty active (I suppose there can be some periods of time when there are no new messages but they unlikely exceed 1-2 minutes.)
