### ISSUE TITLE
Connection Lost 1.95.2 n8n

### ISSUE THREAD

**Issue by trgalusti** [n8n-io/n8n#15949]
### Bug Description

After upgrading to version `1.95.2` on a self-hosted Docker deployment via EasyPanel, the n8n editor constantly shows "🔌 Connection lost" and reconnects every few seconds. All containers (editor, worker, webhook, Redis, Postgres) are running normally and healthy. This causes severe usability issues, including inability to export workflows due to interrupted UI state.

### To Reproduce

1. Open the n8n editor in browser (`https://n8neditor.maquinasixcomercial.com.br`)
2. Wait a few seconds
3. Observe the red "Connection lost" message appear and disappear repeatedly
4. Workflow UI interactions become unstable and exports often fail

### Expected behavior

The UI should maintain a stable connection to the backend and only disconnect if the backend or network fails.

### Operating System

Operating System: Ubuntu 22.04 (Docker, managed via EasyPanel)

### n8n Version

1.95.2

### Node.js Version

Node.js Version: 18.16.0 (via official Docker image n8nio/n8n:latest

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @trgalusti,

We have created an internal ticket to look into this which we will be tracking as "GHC-2310" & "CAT-1027"

**Comment by Joffcom** [comment]
Hey @trgalusti 

Can you upgrade to 1.97.0 where this issue has been resolved.

**Comment by trgalusti** [comment]
How can i do this? On the documentation? I'm afraid to lost my workflows

**Comment by Joffcom** [comment]
@trgalusti I have no idea how you would do it with easy panel but if lets you set the docker image you just swap out :latest with :next

**Comment by arladmin** [comment]
Hi @Joffcom , the issue still persists in v1.95.3, in my docker based n8n instance.

![Image](https://github.com/user-attachments/assets/d8c5b894-dcde-491d-b7f4-84bb74c0a454)

**Server logs:**
```
2025-06-04T04:29:38.469Z | debug | Skipped browserId check on /rest/push {"file":"auth.service.js","function":"resolveJwt"}

2025-06-04T04:29:38.469Z | warn | Origin header does NOT match the expected origin. (Origin: "<my-n8n-domain>", Expected: "<my-n8n-domain>:443") {"scopes":["push"],"headers":{"host":"<my-n8n-domain>","origin":"https://<my-n8n-domain>","x-forwarded-proto":"https","x-forwarded-host":"<my-n8n-domain>:443"},"file":"index.js","function":"handleRequest"}

2025-06-04T04:29:40.464Z | debug | Skipped browserId check on /rest/push {"file":"auth.service.js","function":"resolveJwt"}

2025-06-04T04:29:40.465Z | warn | Origin header does NOT match the expected origin. (Origin: "<my-n8n-domain>", Expected: "<my-n8n-domain>:443") {"scopes":["push"],"headers":{"host":"<my-n8n-domain>","origin":"https://<my-n8n-domain>","x-forwarded-proto":"https","x-forwarded-host":"<my-n8n-domain>:443"},"file":"index.js","function":"handleRequest"}

2025-06-04T04:29:42.464Z | debug | Skipped browserId check on /rest/push {"file":"auth.service.js","function":"resolveJwt"}

2025-06-04T04:29:42.464Z | warn | Origin header does NOT match the expected origin. (Origin: "<my-n8n-domain>", Expected: "<my-n8n-domain>:443") {"scopes":["push"],"headers":{"host":"<my-n8n-domain>","origin":"https://<my-n8n-domain>","x-forwarded-proto":"https","x-forwarded-host":"<my-n8n-domain>:443"},"file":"index.js","function":"handleRequest"}
```

**Comment by arladmin** [comment]
Hi @Joffcom .

This issue is still ongoing, so could we at least open it back up?

**Comment by tomi** [comment]
@arladmin yes there seems to be an issue if the reverse proxy is configured in such a way that it includes port in one header and omits it from the other. As a workaround, you could change your reverse proxy configuration to format both the `origin` and `x-forwarded-host` the same way

**Comment by jmls** [comment]
so we need to modify an proxy to set those header values to the same host ?

**Comment by tomi** [comment]
If you n8n instance is behind a reverse proxy, you must make sure the `Origin` and `X-forwarded-host` headers have the same format. E.g. if one has port, the other must also have the port

**Comment by arc64** [comment]
Fixed in [n8n@1.112.0](https://github.com/n8n-io/n8n/releases/tag/n8n%401.112.0) (as it was mentioned in description of this released [PR#19242](https://github.com/n8n-io/n8n/pull/19242)
