### ISSUE TITLE
AWS Lambda Node - Persistent "Missing Authentication Token" Error

### ISSUE THREAD

**Issue by raddish007** [n8n-io/n8n#16902]
Hello,

I am unable to invoke an AWS Lambda function in the us-east-1 region on my n8n Cloud instance (version 1.100.1). I am consistently getting a 403 Forbidden - Missing Authentication Token error.

We have confirmed:

My IAM User permissions are correct.

My AWS Credentials are valid and test successfully.

The JSON payload being sent to the function is correct.

The problem is that the AWS Lambda node appears to have a bug that prevents it from calling a function in a non-default region. We have tried every possible solution:

The node has no "Region" field or "Add option" button.

The node's validation rejects the full function ARN, so I cannot specify the region that way.

Setting a "Custom Endpoint" for the Lambda service (https://lambda.us-east-1.amazonaws.com) in the credential settings does not fix the error.

My workflow is completely blocked by this issue. Can you please investigate why the AWS Lambda node is failing to send the authentication signature correctly?

### core

- n8nVersion: 1.100.1
- platform: docker (cloud)
- nodeJsVersion: 22.16.0
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

### client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/137.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-07-01T20:43:58.206Z}

**Comment by Joffcom** [comment]
Hey @raddish007,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-2863".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Thanks for reporting this issue! We’ve attempted to reproduce the problem, but unfortunately, we weren’t able to replicate it. It’s possible there was some environmental or other variable that prevented us from seeing the same behavior.

I have done this test using `1.101.0` and I see the below.

![Image](https://github.com/user-attachments/assets/fdcc1eb0-48e6-40b8-82da-52c856c00245)

When you say a `non-default region` what do you mean?

If you’re still encountering this issue, please provide any additional details or steps to reproduce it, and we’d be happy to investigate further. Thanks for your understanding!

**Comment by DavidHruby1** [comment]
I also have the same issue. Using the AWS Lambda node it can not authenticate me even though everything is correct - I triple checked it and tried everything. In AWS CLI I can normally invoke the function without problems but when I try it with the AWS Lambda Node it doesn't work meaning the error is indeed in the AWS Lambda node! For now I got around using HTTP Request but you should fix it

**Comment by Joffcom** [comment]
As we haven’t heard back from you, we’re going to close this issue to keep things organized. But don’t worry, if you have more information or need further assistance, you’re welcome to reopen the issue anytime or create a new one. We’re always happy to help! 

Thanks for reaching out and have a great day! If this was closed by mistake and you have been waiting for us let me know and I can also re-open it.

**Comment by raddish007** [comment]
Unfortunately it didn’t resolve but I moved on to my own custom platform
that met the needs I had for my project.

_____________________________
Carla Engelbrecht, Ed.D.
***@***.***
m: (646) 896-9330​
LinkedIn​ /carlaeng <http://www.linkedin.com/in/carlaeng>
