### ISSUE TITLE
Form trigger always looping

### ISSUE THREAD

**Issue by s-semaya** [n8n-io/n8n#23262]
### Bug Description

When I click on the next form, an infinite loop appears, and it does not proceed to the next form.

before n8n version 2.0, it can load properly.

### To Reproduce

Just make node "On form submission" and make switch node and node "next from page"

<img width="961" height="648" alt="Image" src="https://github.com/user-attachments/assets/16ea24ed-2956-4f68-bf24-24a11f8322da" />

<img width="1339" height="770" alt="Image" src="https://github.com/user-attachments/assets/82a3b99b-57d5-48a1-98d1-3ef640b2a8f5" />

### Expected behavior

Can load to the next form like before version 2.0

### Debug Info

# Debug info

## core

- n8nVersion: 2.1.0
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: b40e5767-9497-41ce-b2ba-9283c4a530c1

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-12-16T07:08:23.471Z

### Operating System

Windows 11

### n8n Version

2.1.0

### Node.js Version

22.21.1

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

**Comment by jerinthomascarmel** [comment]
Yeah , it is working perfect.
When you  first fill the "on submission form" node form , then it routes towaards to the "next form page " node via switch. 
There it is waiting for you to fill the "next form page" node . 
When you submit the first form , never close window, next form will be appear in the same window itself.

**Comment by Rugiagialia** [comment]
i think this is related to following community question - https://community.n8n.io/t/form-workflow-stuck-on-waiting-page-after-upgrade-cors-error-with-origin-null/

**Comment by s-semaya** [comment]
> Yeah , it is working perfect. When you first fill the "on submission form" node form , then it routes towaards to the "next form page " node via switch. There it is waiting for you to fill the "next form page" node . When you submit the first form , never close window, next form will be appear in the same window itself.

i knew your solution you mentioned. But,  it's already minimize of my screen, so i never close window before. Here's my new update of SS.
You can try by yourself and perhaps can see the same problem. it's not direct to "next form page"

<img width="1339" height="770" alt="Image" src="https://github.com/user-attachments/assets/7a2ea3e2-eac3-4460-8320-4ad7705e519e" />

**Comment by MookieLian** [comment]
<aside>

Thank you for raising this issue, the first step of triage is completed, and it has been routed internally for further investigation.

> [Form trigger always looping](https://github.com/n8n-io/n8n/issues/23262#top) #23262

---

_Added `n8n Form Trigger node version 2.4 (Latest)` trigger into workflow, attached an another node with page types: `Next Form Page` and `Form Ending` and ran workflow. Observe that the workflow gets stuck in the canvas, and fails on the backend with the following error:_

<img width="639" height="354" alt="Image" src="https://github.com/user-attachments/assets/9e5261da-0e18-46c1-b58d-5269652d90bb" />

### Additional notes

- _The same workflow succeeds when the downgrading n8n to `1.123.5` or `2.0.2` and using `n8n Form Trigger node version 2.3 (Latest version: 2.4)` instead._

- _`Next Form Page` or `Form Ending` page type nodes do not affect this, and the same behaviour is observed without them._

`#triage:complete`

</aside>

**Comment by gndario-star** [comment]
For me is also happening, but it is in the first node trigger.  "On form submission".  After submit the form, not data is arriving / receiving.  My n8n is in version 2.0.2

**Comment by krisn0x** [comment]
Hey all, this is fixed in 2.1.2 and 2.2.0. #23452

**Comment by nihaals** [comment]
> For me, the CORS issue is still present with 2.1.2, and the workaround described under https://community.n8n.io/t/form-workflow-stuck-on-waiting-page-after-upgrade-cors-error-with-origin-null/236694 is still needed.

Same, might be worth making a new issue so this isn't lost.

**Comment by nihaals** [comment]
> Just checking, did you also update any worker instances if you run any?

@krisn0x There's only one instance. The specific source of my issue is that without `allow-same-origin`, cookies aren't passed with the form POST which breaks an auth proxy that worked fine previously however:
https://github.com/n8n-io/n8n/blob/9fc820fbaf6172652bad099717b6ed20b7829124/packages/cli/templates/form-trigger.handlebars#L991-L999

Without the auth proxy cookie, the POST just gets given a redirect to authenticate. I haven't checked if the auth proxy is the only issue (i.e. if removing it results in no form issues) but as the proxy is needed in prod I've just added `allow-same-origin` which fixed the issue. n8n doesn't support `N8N_JWT_AUTH_HEADER` anymore but I assume this kind of setup is still expected to work if you use n8n's SSO/local accounts.

**Comment by krisn0x** [comment]
@nihaals Thanks, yes this looks like a natural consequence from the recent changes that aim to tighten security. Let me check back with the team on this.

**Comment by nihaals** [comment]
> We recently released a fix in [n8n@2.2.3](https://github.com/n8n-io/n8n/releases/tag/n8n%402.2.3) that may resolve this issue.
> 
> Could someone please confirm whether the problem persists after updating to version 2.2.3 or later?

@ShireenMissi 2.2.3 didn't fix https://github.com/n8n-io/n8n/issues/23262#issuecomment-3694138661.

**Comment by jhaumont** [comment]
Hello
I guess this PR https://github.com/n8n-io/n8n/pull/23795 will fix the issue ?

**Comment by jhaumont** [comment]
Hello
Same issue on my side. We have an oauth2 proxy in front of n8n (without, it works, with, forms loops).
(currently have a ticket on n8n support)

**Comment by ThankYouFuture** [comment]
> > Hello all,
> > I'm still seeing a CORS issue on the n8n 2.2.3 when using a single Form node. There was no issue with Form trigger on 2.0.2.
> > <img alt="Image" width="1953" height="416" src="https://private-user-images.githubusercontent.com/204303862/533140461-620e2a65-eb87-40db-8419-fe752e5a42d8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg0NDM1MjAsIm5iZiI6MTc2ODQ0MzIyMCwicGF0aCI6Ii8yMDQzMDM4NjIvNTMzMTQwNDYxLTYyMGUyYTY1LWViODctNDBkYi04NDE5LWZlNzUyZTVhNDJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExNVQwMjEzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWJjZTM0OTIxMWVkNDIyOTBmMjhhZmY4NmZiZjEzMjAwMDc2MGRhNzk3NzQ4NmJlZWIzZGJiMmQyY2ZkMmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ez4rzZKHtD9rpIN1r4Xr4tSqVinioj4JH93etK1WvZQ"> <img alt="Image" width="1250" height="309" src="https://private-user-images.githubusercontent.com/204303862/533140502-4e3a142c-4081-4adc-ba90-a7d183bfab12.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg0NDM1MjAsIm5iZiI6MTc2ODQ0MzIyMCwicGF0aCI6Ii8yMDQzMDM4NjIvNTMzMTQwNTAyLTRlM2ExNDJjLTQwODEtNGFkYy1iYTkwLWE3ZDE4M2JmYWIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExNVQwMjEzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmQwOWJiYTk1OWJmOGUxNWU3OTcwZTZlZmJjYmFhYWRhYzU0NGJhMGY5OTNiNmE0ODM0NmZlYmQ1YzM1Y2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-fg7vI-giVQfFzK64ZuGXJXh0Ejjk7h1QjE5o2vdmSg">
> > I'm hosting n8n container locally(single instance, no workers), and I have a cloudflared container in the same docker network with n8n instance to make n8n internet accessible.
> > The Form trigger always looping after the submit button is clicked. And CORS related errors can be seen in the browser devtools.
> > Thank you. Appreciate your advice.
> 
> May I check if anyone tried version 2.3.5? From myside, it still has the same CORS related issue.
> 
> <img alt="Image" width="1191" height="434" src="https://private-user-images.githubusercontent.com/204303862/536009754-b9fb60d7-2d2a-4a5b-b3e2-9252dfac957e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg4NTUzMDMsIm5iZiI6MTc2ODg1NTAwMywicGF0aCI6Ii8yMDQzMDM4NjIvNTM2MDA5NzU0LWI5ZmI2MGQ3LTJkMmEtNGE1Yi1iM2UyLTkyNTJkZmFjOTU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExOVQyMDM2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODdjMzA1ZWMwYTk3YmM1ZWUyYzIzZTAxZTkzNzQ4ZWY3MjM4ZDgyYjMwMzE1MDVjZjY0MTUwZDA2YzNmYzVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-ei9bpf_zJjKIwoi4y6YQq1cBHbSEUH7jT4QC07vgqE">

I did install last version 2.3.6, and I still have the same issue. (I'm using CloudFlare Zero Trust)

<img width="978" height="580" alt="Image" src="https://github.com/user-attachments/assets/4dac0ebf-622f-4312-a96e-da300a9be693" />

**Comment by ThankYouFuture** [comment]
Just a follow-up to my last message. Before version 2, my form process worked very well with Cloudflare Zero Trust. Since upgrading to version 2+, I had to add a firewall rule to Cloudflare allowing a bypass for /form* URLs. This makes my application less secure.

**Comment by samuelsemaya** [comment]
> Just a follow-up to my last message. Before version 2, my form process worked very well with Cloudflare Zero Trust. Since upgrading to version 2+, I had to add a firewall rule to Cloudflare allowing a bypass for /form* URLs. This makes my application less secure.

Hope it can be fixed like the result output in the version before v2, without adding a bypass.

**Comment by nico-leb** [comment]
Some more insights : 

n8n needs both the host and the complete URL to be configured (with `https`) . Our previous docker-compose setup  failed to make this distinction and only populated the host value in both places. The "form waiting" was appended  to the current domain and generate CORS errors. 

So make sure your configuration properly differentiates the host and URL and not using  the same environment variables.

<img width="1034" height="460" alt="Image" src="https://github.com/user-attachments/assets/0df196b3-0717-41f5-a805-0369edc4bcd7" />

**Comment by jhaumont** [comment]
@nico-leb yes, and it's not working :/

**Comment by Archalbc** [comment]
Hello :)

Got the same issue on my n8n self-hosted on kubernetes using version 1.123.11. I tried to update to 1.123.18 and the issue is still here with my simple form trigger which infinite loop with a Origin:null value.

I had to downgrade to 1.123.5 as a temporary solution, but now this is more critical since the release of the CVE : 
https://github.com/n8n-io/n8n/security/advisories/GHSA-6cqr-8cfr-67f8
which recommend to upgrade to 1.123.17 at least :(

Everything is under the same DNS using httpS.
But we use one ingress to allow public endpoint like /webhook for trigger like Slack.
And another ingress for "/" with a OIDC/Okta configuration for authentication.
No issue with this configuration until version 1.123.6 (i guess where the issue appear).
A solution would be to add a path for "/form" to the public ingress endpoint like /webhook, but since we use forms only for internal purpose, this is NOT a solution we consider (and it's quite bad for security reasons).

My N8N_PROTOCOL is http since the https termination is done at the Ingress ALB level which route the traffic to my n8n pod using http/80.

**Comment by jhaumont** [comment]
Hello
Update from the support : they will work on a fix in the week of Feb 23
