### ISSUE TITLE
Notion Trigger (Beta) triggers unwanted and buggy executions

### ISSUE THREAD

**Issue by manu7823** [n8n-io/n8n#5846]
**Describe the bug**
Strange phantom executions popping up in the execution log for workflows using the "Notion Trigger (Beta)" pageAddedToDatabase or pageUpdatedInDatabase Trigger. There were no pages added or updated in Notion around the time those executions got triggered.

<img width="1332" alt="Bildschirm­foto 2023-03-30 um 18 39 23" src="https://user-images.githubusercontent.com/53856345/228912105-1687fb7e-ed68-4339-9125-f4f762aa351a.png">

If I try to stop them, on the workflow page, I get an Execution Not Found error.

<img width="436" alt="Bildschirm­foto 2023-03-30 um 18 40 16" src="https://user-images.githubusercontent.com/53856345/228912344-89c08584-a342-42a9-afa5-839a2e571708.png">
<img width="410" alt="Bildschirm­foto 2023-03-30 um 19 08 25" src="https://user-images.githubusercontent.com/53856345/228912472-046f377e-3e5e-4708-937f-f2f13ff75b04.png">

**To Reproduce**

1. Add new workflow with a "Notion Trigger (Beta)" Trigger
2. Connect a Notion account
3. Select 1 Minute as polling interval
4. Select a random database 
5. Activate simplify
6. Add a random second step, for example a Set Transformer (not sure if this is necessary at all)
7. Activate the Workflow 
8. Wait until the first endless executions are popping up (in general, 2 to 4 per day)

**Expected behavior**
The executions should not be started because there was no triggering event.

**Environment (please complete the following information):**

Current n8n Version 0.222.0 running on an Hetzner CPX11 Instance installed in the [recommended way](https://docs.n8n.io/hosting/installation/server-setups/hetzner/) using Docker.

- OS: Ubuntu Linux 22.04
- n8n Version: 0.222.0
- Node.js Version: not sure 
- Database system: SQLite
- Operation mode: own

**Additional context**

**Comment by Joffcom** [comment]
Hey @manu7823,

I noticed you have the version of n8n as 0.220.0 which was released earlier today so it is probably too soon to see if the issue is present in this version. What version did you first notice the issue in?

Normally when you see the execution could not be found message it is down to something odd with the database, What is the size of your sqlite file at the moment and do you have it set to delete old data? I know there was a bit of an issue with the Notion trigger missing records but that was resolved neat the end of last year.

**Comment by manu7823** [comment]
Hi @Joffcom,

thank you for the really fast response!

I updated today, hoping the issue gets resolved. I set up the instance on March 13th with the then current version, I think it was 0.219.1 and have had the problem ever since.

The database.sqlite file has 2.5MB. I don't know if it set to delete old data. I have not made any settings besides the ones in the [Hetzner Setup guide](https://docs.n8n.io/hosting/installation/server-setups/hetzner/). Where can I check the setting?

**Comment by Joffcom** [comment]
Hey @manu7823,

That sort of size sounds ok 🤔 I will set up a test a bit later today to see if I can reproduce this.

**Comment by Joffcom** [comment]
Hey @manu7823,

Are you still seeing this? I have had a Notion trigger running for a few months now and have not seen it happen.

**Comment by manu7823** [comment]
Hi @Joffcom, yes still seeing it running on 0.224.4

<img width="1442" alt="Bildschirmfoto 2023-07-20 um 11 59 01" src="https://github.com/n8n-io/n8n/assets/53856345/0132f06c-e649-4275-a912-6f66e7205eeb">

**Comment by Joffcom** [comment]
Hey @manu7823,

Looking at that image I wonder if it is related to the database size, How large is your SQLite file and do you have data pruning enabled? I would also be tempted to swap from Own to Main mode as well to see if that helps.

**Comment by manu7823** [comment]
hey @Joffcom,

the SQLite file is 2.7GB. I think data pruning is disabled if that's not the default config of the docker image. I upgraded to 0.236.3 3 hours ago and since then no new "phantom" execution has occurred.

**Comment by manu7823** [comment]
Hi @Joffcom, 

It's still not working like expected but the behaviour has changed since I have updated from 0.222.0 to 0.236.3.

The executions still get randomly triggered by the notion tigger node, but not longer shown as running for 0s. Instead they are shown as Could not complete at the global execution board.

<img width="1409" alt="Bildschirmfoto 2023-07-24 um 16 08 48" src="https://github.com/n8n-io/n8n/assets/53856345/1f28b335-edf1-4696-8177-3967a3203a8e">

Also at the workflow execution logs something changed. There I get "Status unknow 0s" and a 504 gateway timeout error at the notion trigger node.

<img width="1932" alt="Bildschirmfoto 2023-07-24 um 16 13 53" src="https://github.com/n8n-io/n8n/assets/53856345/59cd9559-42cf-4a09-a717-ce8fa750f783">

<img width="2522" alt="Bildschirmfoto 2023-07-24 um 16 14 26" src="https://github.com/n8n-io/n8n/assets/53856345/db364005-e795-4aab-8176-55170b3cbfb4">

Maybe that helps?

**Comment by Joffcom** [comment]
Hey @manu7823,

Oddly that does help, That error is coming back from something to say n8n can't connect. We did release a change in 236 that shows an actual error message if hit so I suspect this is part of that. The good news is as there is an error it looks like it might be a connectivity issue although we shouldn't be logging the attempt at all.

Any chance you could share your workflow JSON with me?
