### ISSUE TITLE
Console error: Could not override experiment SyntaxError: "undefined" is not valid JSON

### ISSUE THREAD

**Issue by HenriChabert** [n8n-io/n8n#7712]
**Describe the bug**
The home of n8n is raising this console error. It seems that error comes from [this row](https://github.com/n8n-io/n8n/blob/f1e7ef01173ca43a185ee8aed0a47f7bc7030b83/packages/editor-ui/src/stores/posthog.store.ts#L44).

I checked, this error dos not appear on an instance having the exact same settings under previous version.

**To Reproduce**

1. Go to the main URL
2. Open the dev console
3. Following error should appear
<img width="609" alt="image" src="https://github.com/n8n-io/n8n/assets/47319201/fd8ae557-5aee-4429-bb9e-e5b932dd43a4">

I checks
**Expected behavior**

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version: 1.15.2 (It works on 1.14.2)
- Node.js Version: 18.18.2 (Using official Docker image)

**Additional context**
When placing a debug point on the code, I get the following value for `useStorage(LOCAL_STORAGE_EXPERIMENT_OVERRIDES)`:
```
{
    "__v_isShallow": false,
    "dep": {
        "w": 0,
        "n": 0
    },
    "__v_isRef": true,
    "_rawValue": "undefined",
    "_value": "undefined"
}
```

**Comment by Joffcom** [comment]
Perfect, can you try on 1.16.0 and see if you have the issue on that release as well just to rule out anything special that I may have set?

Or if you can share your docker configuration I can test using that to see if the issue has been resolved already.

**Comment by netroy** [comment]
I believe this was fixed in https://github.com/n8n-io/n8n/pull/7603, and released in 1.16.0.

**Comment by HenriChabert** [comment]
Hello @Joffcom,
Here is my docker configuration:
```
version: "3.7"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_app
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - traefik.enable=false
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_TUNNEL_URL=https://${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/n8n/n8n-local-files:/files

volumes:
  n8n_data:
    external: true
  cache:
```

**Comment by HenriChabert** [comment]
> I believe this was fixed in #7603, and released in 1.16.0.

Thanks @netroy ! It is not blocking for me so I will wait for the official release.

**Comment by Joffcom** [comment]
That is perfect @HenriChabert using your config on `1.15.2` I get the issue and as soon as I swap it to `1.16.0` it is no longer there so I am fairly confident this is resolved.

For now I think I will move this to closed and you still see it after upgrading (possibly later today) let me know and we can open it back up again.
