### ISSUE TITLE
Unable connect to a MySQL database from SQL Agent

### ISSUE THREAD

**Issue by pmoralesp** [n8n-io/n8n#8166]
**Describe the bug**
Unable connect to a MySQL database from SQL Agent if server doesn't support SSL.

**To Reproduce**

1. Build a simplest SQL Agent with chat trigger and any model:
![image](https://github.com/n8n-io/n8n/assets/5074517/a7e12922-972a-4e31-a154-10dee106895b)

2. Select a Mysql credential:

![image](https://github.com/n8n-io/n8n/assets/5074517/b7989cfe-ef0e-44aa-8e61-d7390591fa8b)

3. Test mysql connection

![image](https://github.com/n8n-io/n8n/assets/5074517/820ffc2e-2dac-4c38-ab2e-a2e45eb92787)
![image](https://github.com/n8n-io/n8n/assets/5074517/32027aaf-8c80-4ed7-bdfd-913c3d661513)

4. Then execute SQL Agent node and see the error

![image](https://github.com/n8n-io/n8n/assets/5074517/d801a619-3364-46dd-bebd-2774994ca84f)

```
Error: Server does not support secure connnection
    at ClientHandshake.handshakeInit (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/commands/client_handshake.js:120:21)
    at ClientHandshake.execute (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/commands/command.js:45:22)
    at PoolConnection.handlePacket (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Socket.Readable.push (node:internal/streams/readable:245:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Expected behavior**
Connect to mysql even if server doesn't support ssl

**Environment (please complete the following information):**

- n8n Version Docker v1.22.1

**Additional context**
MySQL pure node works as expected with the same credential
Maybe [here](https://github.com/n8n-io/n8n/blob/master/packages/%40n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/other/handlers/mysql.ts#L14) is the problem? I'm trying to figure out by myself in order to collaborate with PR's someday

**Comment by Joffcom** [comment]
Hey @pmoralesp,

Thanks for the report, I have put in a PR that will fix this although it is rare to see a MySQL server not configured to support some kind of SSL/TLS.

I will mark this as closed for now and once we have merged and released the update that includes this change I will pop a note back on here to let you know.

Let me know if you have any questions about this.

**Comment by mookymook** [comment]
Hi,
I have the same issue, any update on this ?

**Comment by FelipeVeiga** [comment]
same problem here
it must have this option, exemple how can i test in localhost ? 
please, fix it!

thank you!

**Comment by sogjugz** [comment]
Hi, looks like the issue still persist. Maybe any update on this?
