### ISSUE TITLE
ERROR: Gmail error response [400]: Invalid label: UNREAD,INBOX

### ISSUE THREAD

**Issue by mihha** [n8n-io/n8n#902]
**Describe the bug**
Using GMail node, you can't fetch all messages by IDs "INBOX" and "UNREAD" combined

**To Reproduce**
Steps to reproduce the behaviour:

You can see the problem in the following video
https://streamable.com/ji8gfb

**Expected behaviour**
You can fetch messages by "INBOX" and you can fetch messages by "UNREAD" if you use them separately. If you use them combined, you get an error. 

It is either that:
1. GMail node interface should forbid selection of multiple IDs (which is wrong because you should be able to fetch messages by multiple IDs)

2. this is truly a bug somewhere

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n Version 0.79.0
 - Node.js Version v14.9.0

**Additional context**
Full error reported:

`
Error: Gmail error response [400]: Invalid label: UNREAD,INBOX
    at Object.googleApiRequest (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Gmail/GenericFunctions.js:34:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.execute (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Gmail/Gmail.node.js:336:40)
    at async /usr/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:369:47`

**Comment by Rupenieks** [comment]
Hi @mihha ,

I've fixed the issue since. I'll update you when the fix has been released with the newest version of n8n.

Thanks for the detailed bug report. 

All the best,
Ronald

**Comment by mihha** [comment]
Hi,

not a problem at all. I am happy to hear that my report helped you to see the problem and fix it

Regards,
Igor

**Comment by janober** [comment]
Fix got released with n8n@0.80.0

**Comment by mihha** [comment]
Guys, I have to reopen this issue

I am afraid that it isn't solved yet. It is the truth that node doesn't throw the error any more in case you are using multiple label IDs (INBOX, UNREAD) but another thing happens

In case you don't have any UNREAD messages in the INBOX, node will now fetch all the messages (limited by the number of set under the Limit parameter)

For example, I have configured node with the following 
![image](https://user-images.githubusercontent.com/3791124/92116407-1480a600-edf4-11ea-8e9f-7e1b09ab0991.png)

If you execute that node with no unread messages in inbox
![image](https://user-images.githubusercontent.com/3791124/92116495-324e0b00-edf4-11ea-90ae-afdeff4732a9.png)

you will get this after some time of processing (I have deliberately hidden the results because of privacy reasons)
![image](https://user-images.githubusercontent.com/3791124/92116667-6b867b00-edf4-11ea-91f6-cc2a1d92b9ba.png)

I can also see from the fetched items that they are fetched from different IDs (labels) and not from the Inbox.

Part of the messages are from INBOX, part of the messages are from "All emails", part of them are from TRASH etc

Something is not quite right 🤔

Thank you for the effort you spent so far in resolving this. We are close to the final working solution

Regards,
Igor
